name: Deploy Zomboid Server
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Get short SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7
      - run: echo Short SHA - ${{steps.short-sha.outputs.SHA}}
